export enum QrDisplaySizeEnum {
    A3 = 'A3',
    A4 = 'A4',
    A5 = 'A5',
    A3_LANDSCAPE = 'A3_LANDSCAPE',
    A4_LANDSCAPE = 'A4_LANDSCAPE',
    A5_LANDSCAPE = 'A5_LANDSCAPE',
    INSTAGRAM_STORY = 'INSTAGRAM_STORY',
    INSTAGRAM_POST = 'INSTAGRAM_POST',
    DESKTOP_1080P = 'DESKTOP_1080P',
}
